# ===================================================================
# HYPRIDLE CONFIG
# ===================================================================

general {
    after_sleep_cmd = hyprctl dispatch dpms on
    ignore_dbus_inhibit = false
}

# --- Screen Off ---
listener {
    timeout = 1800                                  # 30 minutes
    on-timeout = hyprctl dispatch dpms off          # Turn displays off
    on-resume = hyprctl dispatch dpms on
}

# --- System Suspend ---
listener {
    timeout = 3600                                  # 1 hour
    on-timeout = systemctl suspend                  # Suspend the system
}
